asphomework1/Controllers/OrderUpdateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using asphomework1.Models;

namespace asphomework1.Controllers
{
    public class OrderUpdateController : Controller
    {
        // GET: OrderUpdate
        [HttpGet]
        public ActionResult UpdateIndex(string OrderID)
        {
            OrdersService OrderService = new OrdersService();
            ViewBag.select = OrderService.SelectOrderByID(OrderID);
            foreach(var item in (List<asphomework1.Models.Orders>)ViewBag.select)
            {
                ViewBag.orderid = item.OrderID;
                ViewBag.customer = item.CompanyName;
                ViewBag.customerid = item.CustomerID.ToString();
                ViewBag.lastname = item.Lastname;
                ViewBag.employeeid = item.EmployeeID.ToString();
                ViewBag.orderdate = item.OrderDate;
                ViewBag.requireddate = item.RequiredDate;
                ViewBag.shippeddate = item.ShippedDate;
                ViewBag.shippername = item.ShipperName;
                ViewBag.shipperid = item.ShipperID.ToString();
                ViewBag.freight = item.Freight;
                ViewBag.shipname = item.ShipName;
                ViewBag.shipaddress = item.ShipAddress;
                ViewBag.shipcity = item.ShipCity;
                ViewBag.shipregion = item.ShipRegion;
                ViewBag.shippostalcode = item.ShipPostalCode;
                ViewBag.shipcountry = item.ShipCountry;
            }

            EmployeesService EmployeesService = new EmployeesService();
            List<Employees> result = EmployeesService.GetEmployeesName();

            List<SelectListItem> EmployeesData = new List<SelectListItem>();
            EmployeesData.Add(new SelectListItem()
            {
                Text = ViewBag.lastname,
                Value = ViewBag.employeeid
            });
            foreach (var item in result)
            {
                EmployeesData.Add(new SelectListItem()
                {
                    Text = item.LastName,
                    Value = item.EmployeeID.ToString()
                });
                ViewData["EmpData"] = EmployeesData;
            }

            ShippersService ShippersService = new ShippersService();
            List<Shippers> result1 = ShippersService.GetShippersName();

            List<SelectListItem> ShippersData = new List<SelectListItem>();
            ShippersData.Add(new SelectListItem()
            {
                Text = ViewBag.shippername,
                Value = ViewBag.shipperid
            });
            foreach (var item in result1)
            {
                ShippersData.Add(new SelectListItem()
                {
                    Text = item.CompanyName,
                    Value = item.ShipperID.ToString()
                });
                ViewData["ShippersData"] = ShippersData;
            }

            CustomersService CustomersService = new CustomersService();
            List<Customers> result2 = CustomersService.GetCustomerName();

            List<SelectListItem> CustomersData = new List<SelectListItem>();
            CustomersData.Add(new SelectListItem()
            {
                Text = ViewBag.customer,
                Value = ViewBag.customerid
            });
            foreach (var item in result2)
            {
                CustomersData.Add(new SelectListItem()
                {
                    Text = item.CompanyName,
                    Value = item.CustomerID.ToString()
                });
                ViewData["CustomersData"] = CustomersData;
            }

            ViewBag.orderdetail = OrderService.SelectOrderDetailByID(OrderID);

            List<SelectListItem> ProductsData = new List<SelectListItem>();
            List<List<SelectListItem>> getProductList = new List<List<SelectListItem>>();
            ProductsService ProductsService = new ProductsService();
            List<Products> result3 = ProductsService.GetProductName();
            for (int i = 0; i < ViewBag.orderdetail.Count; i++)
            {
                foreach (var item in result3)
                {
                    ProductsData.Add(new SelectListItem()
                    {
                        Text = item.ProductName,
                        Value = item.ProductID.ToString(),
                        Selected = item.ProductID.Equals(ViewBag.orderdetail[i].ProductID)
                    });
                    ViewData["ProductsData"] = ProductsData;
                }
                getProductList.Add(new List<SelectListItem>(ProductsData));
                ProductsData.Clear();
            }

            ViewBag.ProductData = getProductList;

            List<Products> result4 = ProductsService.GetProductUnitPrice();
            List<SelectListItem> PriceData = new List<SelectListItem>();

            ViewBag.PriceData = PriceData;
            foreach (var item in result4)
            {
                PriceData.Add(new SelectListItem()
                {
                    Value = item.UnitPrice.ToString()
                });
                ViewBag.PriceData = PriceData;
            }

            return View();


            
        }


        [HttpPost()]
        public ActionResult UpdateIndex(Models.InsertSearch update)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    OrdersService OrdersService = new OrdersService();
                    OrdersService.DeleteOrderDetailByID(update.OrderID);
                    OrdersService.updateorder(update);
                    return RedirectToAction("../Employees/Index");
                }
                catch (Exception ex)
                {
                    throw ex;
                }

            }
            return View(update);
        }
    }
}

asphomework1/Views/OrderUpdate/UpdateIndex.cshtml
@model asphomework1.Models.InsertSearch
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>InsertIndex</title>

</head>
<body>
    @using (Html.BeginForm("UpdateIndex", "OrderUpdate", FormMethod.Post, new { id = "Form3" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div>
            <h3>修改訂單</h3>
        </div>
        <div>
            <table class="table" style="width:75%">
                <tr>
                    <td>訂單編號</td>
                    <td>@Html.TextBoxFor(Models => Models.OrderID, new { Value = ViewBag.orderid,style="border:0"})</td>
                </tr>
                <tr>
                    <td>客戶名稱</td>
                    <td>
                        @Html.DropDownListFor(Models => Models.CustomerID, (List<SelectListItem>)ViewData["CustomersData"])
                        @Html.ValidationMessageFor(Models => Models.CustomerID)
                    </td>
                </tr>
                <tr>
                    <td>負責員工名稱</td>
                    <td>
                        @Html.DropDownListFor(Models => Models.EmployeeID, (List<SelectListItem>)ViewData["EmpData"])
                        @Html.ValidationMessageFor(Models => Models.EmployeeID)
                    </td>
                </tr>
                <tr>
                    <td>訂單日期</td>
                    <td>
                        @Html.TextBoxFor(Models => Models.OrderDate, new { @type = "date",@Value=ViewBag.orderdate})
                        @Html.ValidationMessageFor(Models => Models.OrderDate)
                    </td>
                    <td>需要日期</td>
                    <td>
                        @Html.TextBoxFor(Models => Models.RequiredDate, new { @type = "date" ,@Value = ViewBag.requireddate})
                        @Html.ValidationMessageFor(Models => Models.RequiredDate)
                    </td>
                </tr>
                <tr>
                    <td>出貨日期</td>
                    <td>
                        @Html.TextBoxFor(Models => Models.ShippedDate, new { @type = "date" ,@Value = ViewBag.shippeddate})
                        @Html.ValidationMessageFor(Models => Models.ShippedDate)
                    </td>
                </tr>
                <tr>
                    <td>出貨公司名稱</td>
                    <td>
                        @Html.DropDownListFor(Models => Models.ShipperID, (List<SelectListItem>)ViewData["ShippersData"])
                        @Html.ValidationMessageFor(Models => Models.ShipperID)
                    </td>
                </tr>
                <tr>
                    <td>運費</td>
                    <td>
                        @Html.TextBoxFor(Models => Models.Freight,new { Value = ViewBag.freight, onchange = "totalsum()" })
                        @Html.ValidationMessageFor(Models => Models.Freight)
                    </td>
                </tr>
                <tr>
                    <td>出貨國家</td>
                    <td>
                        @Html.TextBoxFor(Models => Models.ShipCountry,new {Value = ViewBag.shipcountry })
                        @Html.ValidationMessageFor(Models => Models.ShipCountry)
                    </td>
                    <td>出貨城市</td>
                    <td>
                        @Html.TextBoxFor(Models => Models.ShipCity,new { Value = ViewBag.shipcity})
                        @Html.ValidationMessageFor(Models => Models.ShipCity)
                    </td>
                </tr>
                <tr>
                    <td>出貨地區</td>
                    <td>
                        @Html.TextBoxFor(Models => Models.ShipRegion,new { Value = ViewBag.shipregion })
                        @Html.ValidationMessageFor(Models => Models.ShipRegion)
                    </td>
                    <td>郵遞區號</td>
                    <td>
                        @Html.TextBoxFor(Models => Models.ShipPostalCode,new { Value = ViewBag.shippostalcode})
                        @Html.ValidationMessageFor(Models => Models.ShipPostalCode)
                    </td>
                </tr>
                <tr>
                    <td>出貨地址</td>
                    <td>
                        @Html.TextBoxFor(Models => Models.ShipAddress,new { Value = ViewBag.shipaddress})
                        @Html.ValidationMessageFor(Models => Models.ShipAddress)
                    </td>
                    <td>出貨說明</td>
                    <td>
                        @Html.TextBoxFor(Models => Models.ShipName,new { Value = ViewBag.shipname})
                        @Html.ValidationMessageFor(Models => Models.ShipName)
                    </td>
                </tr>
                <tr>
                    <td>訂單金額總計</td>
                    <td><input type="text" id="ordersum" value="" disabled></td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="存檔" />
                    
                        <a class="btnDelete" href="#" onclick="location.href = '../Employees/Index'">刪除</a>
                        <input class="hidOrderId" type="hidden" value='@ViewBag.orderid'  />
                    
                        @Html.ActionLink("回前一頁", "../Employees/Index")
                    </td>
                </tr>
            </table>
        </div>
        <div><h3>訂單明細</h3></div>
        <div>
            <a id="addNewDetial" href="#">新增一筆</a>
            <table class="table" style="width:75%">
                <tr>
                    <td>商品</td>
                    <td>單價</td>
                    <td>數量</td>
                    <td>小計</td>
                    <td></td>
                </tr>
                <tbody id="tbContent">

                    @for (int i = 0; i < ViewBag.orderdetail.Count; i++)
                {
                        <tr>
                            <td>@Html.DropDownListFor(Models => Models.OrderDetails[i].ProductID, (List<SelectListItem>)ViewBag.ProductData[i], new { @class = "ProductID", @onchange = "GetPrice(this)" })</td>
                            <td>@Html.TextBoxFor(Models => Models.OrderDetails[i].UnitPrice, new { @class = "UnitPrice", @id = "UnitPrice", Value = ViewBag.orderdetail[i].UnitPrice, @onchange = "change(this)" })</td>
                            <td>@Html.TextBoxFor(Models => Models.OrderDetails[i].Qty, new { @class = "Qty",@Value = ViewBag.orderdetail[i].Qty, onchange = "Count(this)"  })</td>
                            <td><input type="text" class="detailsum" disabled></td>
                            <td><button type="button" class="btnRemove" onclick="totalsum();">取消</button></td>
                        </tr>
                    }


                </tbody>
            </table>


            @section scripts{
                <script type="text/javascript">
        //明細資料範本
        var trtemplate = $('#tbContent tr').eq(0).html();

        //新增一列名資料
        $("#addNewDetial").click(function (e) {
            $('#tbContent').append('<tr>' + trtemplate + '</tr>');
        });

        //移除TR
        $('#tbContent').on('click', '.btnRemove', function () {
            if ($('#tbContent tr').length > 1)
                $(this).closest('tr').remove();
        });

        //表單送出前置換element name 讓Action 可以讀到OrderDetials
        $('form').submit(function () {
            for (var i = 0 ; i < $('#tbContent tr').length; i++) {
                $('.ProductID').eq(i).attr('name', 'OrderDetails[' + i + '].ProductID');
                $('.Qty').eq(i).attr('name', 'OrderDetails[' + i + '].Qty');
                $('.UnitPrice').eq(i).attr('name', 'OrderDetails[' + i + '].UnitPrice');
            }
        });

        $(".ProductID").change(function (e) {

            $.ajax({
                type: "POST",
                url: "/Customers/GetProdutsUnitPrice",
                data: "ProductID=" + $(".ProductID").val(),
                dataType: "json",
                success: function (response) {

                    $("#UnitPrice").val(response.UnitPrice);
                }
            });
            return false;
        });

        var ordersum = 0;
        var total = 0;
        function GetPrice(item) {
            var price=[];
            var array = @Html.Raw(Json.Encode(@ViewBag.PriceData));

            for(var i = 0 ;i<array.length;i++){
                price[i]=array[i].Value;
            }
            $(item).parent().next('td').children().val(price[item.value-1]);
            var unitprice=$(item).parent().next('td').children().val();
            var qty=$(item).parent().next('td').next('td').children().val();
            if(qty != null){
                total=unitprice*qty;
            }else{
                total=0;
            }

            $(item).parent().next('td').next('td').next('td').children().val(total);
            totalsum();
        }
        //更改單價時，小計跟著變化
        function change(item){
            var unitprice=$(item).closest("input:text").val();
            var qty=$(item).parent().next('td').children().val();
            total=unitprice*qty;
            $(item).parent().next('td').next('td').children().val(total);
            totalsum();
        }
        //更改數量時，小計跟著變化
        function Count(item){
            var unitprice=$(item).parent().prev('td').children().val();
            var qty=$(item).closest("input:text").val();
            total=Math.round(unitprice*qty,1);
            $(item).parent().next('td').children().val(total);
            totalsum();
        }
        function totalsum(){
            ordersum = 0;
            var detailsum = document.getElementsByClassName("detailsum");
            for(var s=0;s<detailsum.length;s++){
                ordersum+=parseInt(detailsum[s].value);
                //console.log(ordersum);
            }
            if($("#Freight").val() != ""){
                ordersum+=parseInt($("#Freight").val());
                document.getElementById("ordersum").value=ordersum;
            }else{

                document.getElementById("ordersum").value=ordersum;
            }
        }
                </script>
            }
        </div>

}
    <script type="text/javascript">
        

        $(".btnDelete").click(function (e) {

            var tr = $(this).closest('tr')
            $.ajax({
                type: "POST",
                url: "/Employees/DeleteOrder",
                data: "OrderID=" + $(this).next().val(),
                dataType: "json",
                success: function (response) {
                    console.log(response);
                }
            });
            
            return false;
        });

    </script>
</body>

</html>